pub const COUNTERS_MAX_REQUEST_LEN: u16 = 32;
pub const FLAGS_MAX_REQUEST_LEN: u16 = 128;
pub const INPUTS_MAX_REQUEST_LEN: u16 = 128;
pub const OUTPUTS_MAX_REQUEST_LEN: u16 = 128;
pub const REGISTERS_MAX_REQUEST_LEN: u16 = 32;
pub const TIMERS_MAX_REQUEST_LEN: u16 = 32;
